language: minimal

dist: xenial

branches:
  only:
    - master

env:
  - LANG=zh_CN.utf8

before_script:
  - sudo bash ./.travis/deps.sh

script:
  - ./build.sh
  - ./.travis/push.sh

deploy:
  provider: releases
  api_key: $GT_TOKEN
  file_glob: true
  file: wechat-devtools-*.tar.xz
  skip_cleanup: true
  overwrite: true
  on:
    branch: master