language: minimal

dist: xenial

branches:
  only:
    - master

env:
  global:
    - LANG=zh_CN.utf8
    - CACHE_DIR=$TRAVIS_BUILD_DIR/.cache

before_script:
  - sudo ./.travis/deps.sh

script:
  - ./build.sh
  - source ./.travis/push.sh

cache:
  directories:
    - $CACHE_DIR

deploy:
  provider: releases
  api_key:
    secure: "K1JrBZWt5aYRmUg7bsldjDLFVwQzq4zMk9f6qrlAxaiq9ZA3ERh69JEueD2fd+x1r5PGMfe5/vfL97I7ef9/9qDgI/DSxTcV3Cg9jpJPduABN77xFwB+0A6lHfLg5994FuBL4SYivsdXH9bkQ2AycV33zEG3ZM245eI/WqS1E3eb/IqaxK9LPFkclGqU1qnWz76ArGSOyjMv2f+pf3brlfCAeN4GfC+YOVsPpp9KqoBc+N66h0BUJkPnGsw5U9HpgRZoxWUX2iTvIoF42lyOm8sYw7sFc05NAW4juuZTDHkLiWcB0vsJ1Shi24z2dmdvsBAIX1oPx8r2Qfbmkc7obI0kk3OWXgf6YGp49kpYAb5TNJVZhpniuSyYDTR2ZuEi0PASh+jnNOiEeY5wk/kym7B7mTAaR7a3Nmz+wfVJIa2QcdNpCJFUmRhqngEERa7HCHU2gO6PGhNwjT7jFmOUyeVlKxZRXKT+mI46Aie3yfSIvT7J3+iQMTb1Q9fSSzqUUms33y22afYE2J8ZpfzSSQDb5DujQwY9kM1mgJtiJtMWXtY3GB2g8uW5tpEHqjQsl2AFFa+NA6WuSFrqMUXrHf16VEgMolI8xFwqzs/F6/9An0PxilfDgI7YaugSfyp9zhAboB08BGXl2HT7gphrPdWpoPIEizth4PqwVv/MN54="
  file: wechat-devtools-$TRAVIS_TAG.tar.xz
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    condition: $TRAVIS_TAG =~ ^[0-9.]+$ 
