language: minimal

dist: xenial

branches:
  only:
    - master

env:
  global:
    - LANG=zh_CN.utf8
    - CACHE_DIR=$TRAVIS_BUILD_DIR/.cache

before_script:
  - sudo ./.travis/deps.sh

script:
  - ./build.sh
  - ./.travis/push.sh

cache:
  directories:
    - $CACHE_DIR

deploy:
  provider: releases
  api_key: $GT_TOKEN
  file_glob: true
  file: wechat-devtools-*.tar.xz
  skip_cleanup: true
  overwrite: true
  on:
    branch: master