language: minimal

dist: xenial

sudo: required

script: ./build.sh

after_script: tar -czf wechat-devtools.tar.gz ./dist

before_deploy:
  - git config --local user.name "sigoden"
  - git config --local user.email "sigoden@gmail.com"
  - export TRAVIS_TAG=${cat ./version}
  - git commit -am 'ci-commit'
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GT_TOKEN
  file: wechat-devtools.tar.gz
  skip_cleanup: true