language: minimal

dist: xenial

env:
  - LANG=zh_CN.utf8

before_script:
  - sudo bash ./.travis/7z.sh

script:
  - ./build.sh
  - ./.travis/push.sh
deploy:
  provider: releases
  api_key: $GT_TOKEN
  file_glob: true
  file: wechat-devtools-*.tar.gz
  skip_cleanup: true
  overwrite: true
